#define IF                101
#define ELIF              102
#define ELSE              103
#define WHILE             104
#define EXIT              105
#define DEF               106
#define PRINT             107
#define INPUT             108
#define RETURN            109
#define AND               110
#define OR                111
#define NOT               112
#define LPAREN            113
#define RPAREN            114
#define STAR              115
#define SLASH             116
#define LT                117
#define GT                118
#define PLUS              119
#define MINUS             120
#define EQUAL             121
#define COMMA             122
#define ASSIGN            123
#define GREATER_OR_EQ     124
#define LESS_OR_EQ        125
#define IDENTIFIER        126
#define DIGIT             127
#define NOT_EQUAL         128
